config/routes.rb
Rails.application.routes.draw do
  get '/data_hubs/:data_hub_id/file_uploads/:id/rename', to: 'file_uploads#rename', as: :rename_file
  
  resources :data_hubs do
    resources :file_uploads
  end
  

  # Defines the root path route ("/")
  root "file_uploads#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bucket.rb
class Bucket < ApplicationRecord
  belongs_to :data_hub
  has_many :data_objects, dependent: :destroy
end

app/models/data_hub.rb
class DataHub < ApplicationRecord
  MAX_STORAGE_QUOTA = 15

  enum :status, {
    active: 0,
    inactive: 1,
    suspended: 2
  }

  enum :plan_type, {
    free: 0,
    premium: 1,
    enterprise: 2,
    unlimited: 3,
    custom: 4,
  }

  has_many :buckets, dependent: :destroy
  has_many :data_objects, dependent: :destroy

  before_save do
    self.drive_id = SecureRandom.urlsafe_base64 if drive_id.nil?
    self.owner_id = 1 # CHANGE: will be replaced with actual user id later
  end
end

app/models/data_object.rb
class DataObject < ApplicationRecord
  PERMITTED_FILE_TYPES = [
    'application/pdf',
    'application/msword',
    'application/vnd.ms-excel',
    'application/vnd.ms-powerpoint',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'application/vnd.oasis.opendocument.text',
    'video/mp4',
    'video/mpeg',
    'video/ogg',
    'video/webm',
    'video/x-msvideo',
    'audio/mpeg',
    'audio/png',
    'audio/wave',
    'audio/aac',
    'audio/midi',
    'image/jpeg',
    'image/png',
    'image/gif',
    'image/svg+xml',
    'image/tiff',
    'text/plain',
    'text/css',
    'text/csv',
    'text/xml'
  ]

  belongs_to :data_hub
  belongs_to :bucket, optional: true
  has_one_attached :file

  validates :file, file_format: true

  before_validation do |data_object|
    data_object.name = file.filename if data_object.name.nil?
    data_object.checksum = file.blob.checksum
    data_object.object_type = file.blob.content_type
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ErrorHandler
end

app/controllers/concerns/error_handler.rb
module ErrorHandler
  extend ActiveSupport::Concern

  included do
    # rescue Standard Errors and log them
  end
end

app/controllers/data_hubs_controller.rb
class DataHubsController < ApplicationController
  before_action :set_data_hub, only: %i[show edit update destroy]

  def index
    @data_hubs = DataHub.all
  end

  def show
  end

  def edit
  end

  def new
    @data_hub = DataHub.new
  end

  def create
    @data_hub = DataHub.new(data_hub_params)

    if @data_hub.save
      redirect_to @data_hub, notice: 'DataHub successfully created'
    else
      render :new
    end
  end

  def update
    if @data_hub.update(data_hub_params)
      redirect_to root_path, notice: 'DataHub successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @data_hub.destroy

    redirect_to root_path, notice: 'DataHub and all assciated data successfully deleted'
  end


  private


  def set_data_hub
    @data_hub = DataHub.find(params[:id])
  end

  def data_hub_params
    params.require(:data_hub).permit(
      :plan_type,
      :region
    )
  end
end

app/controllers/file_uploads_controller.rb
class FileUploadsController < ApplicationController
  before_action :set_data_hub
  before_action :set_data_object, only: [:show, :edit, :update, :destroy, :rename]

  def index
    @data_objects = @data_hub.data_objects
  end

  def show
  end

  def new
    @data_object = @data_hub.data_objects.new
  end

  def create
    @data_object = @data_hub.data_objects.new(file_upload_params)

    if @data_object.save
      redirect_to root_path, notice: 'File uploaded successfully'
    else
      flash.now[:alert] = 'Oops! Something went wrong. File failed to upload'
      render :new
    end
  end

  def edit
  end

  def rename
  end

  def update
    if @data_object.update(file_upload_params)
      redirect_to root_path, notice: 'File uploaded successfully'
    else
      flash.now[:alert] = 'Oops! Something went wrong. File failed to upload'
      render :edit
    end
  end

  def destroy
    @data_object.destroy
    redirect_to root_path, notice: 'File removed successfully'
  end


  private

  def file_upload_params
    params.require(:data_object).permit(
      :name,
      :file,
      :description,
      :data_hub_id,
      :bucket_id,
      :private,
      tags: []
    )
  end

  def set_data_hub
    # short cut for sessions
    return @data_hub = DataHub.first if params[:data_hub_id].blank?

    @data_hub = DataHub.find(params[:data_hub_id])
  end

  def set_data_object
    @data_object = @data_hub.data_objects.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_hubs_helper.rb
module DataHubsHelper
  def plan_type_color(text)
    {
      0 => 'primary',
      1 => 'secondary',
      2 => 'default',
      3 => 'warning',
      4 => 'success'
    }[DataHub::plan_types[text]]
  end
end

app/helpers/file_uploads_helper.rb
module FileUploadsHelper
end

app/views/data_hubs/_form.html.erb
<%= form_with model: data_hub do |form| %>
<p>
  <div class="btn-group btn-group-toggle" data-toggle="buttons">
    <%= form.collection_radio_buttons :plan_type, DataHub::plan_types, :first, :first do |b| %>
      <%= b.label(class: "btn btn-#{plan_type_color(b.text)}") { b.radio_button() + b.text  } %>
    <% end  %>
  </div>
</p>
  <%= form.submit 'Create Data Hub', class: 'btn btn-md btn-primary' %>
<% end %>

app/views/data_hubs/edit.html.erb
<h1>Update Your Data Hub</h1>
<%= render 'form', data_hub: @data_hub %>

app/views/data_hubs/index.html.erb
<h1>Your Hubs</h1>
<br>
<p><%= link_to new_data_hub_path, class: 'btn btn-primary btn-md' do %>
  <i class="bi bi-plus-circle-fill"></i>
  DataHub
<% end %>
</p>

<div class="card-body table-responsive p-0">
  <table class="table table-hover text-nowrap">
    <thead>
      <tr>
        <th></th>
        <th>Drive ID</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @data_hubs.each do |data_hub| %>
        <tr>
          <td> <h6><i class="bi bi-hdd-fill"></i></td>
          <td><%= data_hub.drive_id %></td>
          <td>
            <%= link_to data_hub do %>
             <i class="bi bi-eye-fill"></i>
             View
           <% end %> | 
           <%= link_to data_hub_path(data_hub), data: { turbo_method: :delete } do %>
             <i class="bi bi-trash-fill"></i>
             Delete
           <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/data_hubs/new.html.erb
<h1>Create Your Data Hub</h1>
<%= render 'form', data_hub: @data_hub %>

app/views/data_hubs/show.html.erb
<div class="card col-6">
  <div class="card-header">
    <h1 class="card-title">Your DataHub</h1>
  </div>
  <!-- /.card-header -->
  <div class="card-body p-0">
    <table class="table table-striped">
      <tbody>
        <tr>
          <td>Driver ID:</td>
          <td>
            <%= @data_hub.drive_id %>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>Plan Type:</td>
          <td class="btn btn-sm btn-<%= plan_type_color(@data_hub.plan_type) %>">
            <%= @data_hub.plan_type %>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>Storage Quota:</td>
          <td>
            <%= @data_hub.storage_quota %>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>Used Storage:</td>
          <td>
            <%= @data_hub.used_storage %>%
          </td>
          <td></td>
        </tr>
        <tr>
          <td>Active:</td>
          <td>
            <%= @data_hub.status %>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>Region:</td>
          <td>
            <%= @data_hub.region %>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>Created At:</td>
          <td>
            <%= @data_hub.created_at.strftime('%D, %T') %>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>Modified At:</td>
          <td>
            <%= @data_hub.updated_at.strftime('%D, %T') %>
          </td>
          <td></td>
        </tr>
      </tbody>
    </table>
  </div>
  <!-- /.card-body -->
</div>

app/views/file_uploads/_form.html.erb
<div class="col-md-3">
  <div class="card card-secondary">
    <div class="card-header">
      <h3 class="card-title">Upload Your File</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
      <%= form_with model: [data_hub, data_object], url: url do |form| %>
      <div class="card-body">
        <div class="form-group">
          <div class="input-group">
            <div class="custom-file">
              <%= form.hidden_field :file %>
              <%= form.file_field :file, class: 'btn btn-sm btn-default' %>
            </div>
          </div>
        </div>
      <!-- /.card-body -->
      <%= form.submit 'Submit', class: 'btn btn-secondary' %>
    <% end %>  
  </div>
  <!-- /.card -->
</div>

app/views/file_uploads/edit.html.erb
<%= render 'form', data_hub: @data_hub, data_object: @data_object, url: edit_data_hub_file_upload_path(@data_hub, @data_object) %>

app/views/file_uploads/index.html.erb
<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">Files/Folders</h3>
        <div class="card-tools">
          <div class="input-group input-group-sm" style="width: 150px;">
            <input type="text" name="table_search" class="form-control float-right" placeholder="Search">
            <div class="input-group-append">
              <button type="submit" class="btn btn-default">
                <i class="fas fa-search"></i>
              </button>
            </div>
          </div>
        </div>
      </div>
      <!-- /.card-header -->
      <div class="card-body table-responsive p-0">
        <table class="table table-hover text-nowrap">
          <thead>
            <tr>
              <th>Name</th>
              <th>Owner</th>
              <th>Location</th>
              <th>File<th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @data_objects.each do |data_object| %>
              <% file = data_object.file %>
              <tr>
                <td><h6><%= data_object.name.truncate(80) %></h6></td>
                <td>John Doe</td>
                <td>My DataHub</td>
                <td>
                  <% if file.representable? %>
                    <%= link_to rails_blob_path(file, disposition: "inline"), target: :_blank do %>
                      <%= image_tag file.representation(resize_to_limit: [100, 100]) %>
                    <% end %>
                  <% else %>  
                    <%= link_to rails_blob_path(file, disposition: "attachment"), target: :_blank do %>
                      <%#= image_tag "placeholder.png", alt: "Download file" %>
                      <%= file.filename %>
                    <% end %>
                  <% end %>  
                </td>
                <td>
                  <%= link_to rails_blob_path(file, disposition: "attachment") do %>
                    <h4><i class="bi bi-cloud-arrow-down-fill"></i></h4>
                  <% end %>
                  <%= link_to rename_file_path(@data_hub, data_object) do %>
                    <h4><i class="bi bi-pencil-square"></i></h4>
                  <% end %>
                  <%= link_to data_hub_file_upload_path(@data_hub, data_object), data: { turbo_method: :delete } do %>
                    <h4><i class="bi bi-trash-fill"></i></h4>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <!-- /.card-body -->
    </div>
    <!-- /.card -->
  </div>
</div>

app/views/file_uploads/new.html.erb
<%= render 'form', data_hub: @data_hub, data_object: @data_object, url: data_hub_file_uploads_path(@data_hub) %>

app/views/file_uploads/rename.html.erb
<div class="card card-primary col-6">
  <div class="card-header">
    <h3 class="card-title">Rename</h3>
  </div>
  <%= form_with model: [@data_hub, @data_object], method: :patch, url: data_hub_file_upload_path(@data_hub, @data_object) do |form| %>
    <div class="card-body">
      <div class="form-group">
        <p>
          <%= form.label :name %>
          <%= form.text_field :name, class: 'form-control' %>
          </br>
          <%= form.label :description %>
          <%= form.text_area :description, class: 'form-control' %>
        </p>
      </div>  
    <%= form.submit 'Submit', class: 'btn btn-md btn-primary' %>
    </div>
  <% end %>
</div>

app/views/file_uploads/show.html.erb
<h1>FileUploads#show</h1>
<p>Find me in app/views/file_uploads/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MediaVault</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
      <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <div class="sidebar">
          <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
              <li>
                <p>
                  <!-- i'm cheating here, this will eventually be a session -->
                  <% current_datahub = DataHub.first%>
                  <%= link_to new_data_hub_file_upload_path(current_datahub), class: 'btn btn-primary' do %>
                    <i class="bi bi-cloud-arrow-up-fill"></i>
                    Upload File
                  <% end %>
                </p>
              </li>
              </br>
              <li class="nav-item">
                <p>
                  <%= link_to data_hub_file_uploads_path(current_datahub) do %>
                    <i class="bi bi-house-fill"></i>
                    Home
                  <% end %>
                </p>
              </li>
              <li class="nav-item">
                <p>
                  <%= link_to data_hubs_path do %>
                    <i class="bi bi-hdd-fill"></i>
                    Data Hubs
                  <% end %>
                </p>
              </li>
              <li class="nav-item">
                <p>
                  <%= link_to '#' do %>
                    <i class="bi bi-usb-symbol"></i>
                    Connected Devices
                  <% end %>
                </p>
              </li>
              <li class="nav-item">
                <p>
                  <%= link_to '#' do %>
                    <i class="bi bi-share-fill"></i>
                    Shared Data
                  <% end %>
                </p>
              </li>
              <li class="nav-item">
                <p>
                  <%= link_to '#' do %>
                    <i class="bi bi-clock-fill"></i>
                    Recent
                  <% end %>
                </p>
              </li>
              <li class="nav-item">
                <p>
                  <%= link_to '#' do %>
                    <i class="bi bi-star-fill"></i>
                    Starred
                  <% end %>
                </p>
              </li>
              <li class="nav-item">
                <p>
                  <%= link_to '#' do %>
                    <i class="bi bi-trash-fill"></i>
                    Trash
                  <% end %>
                </p>
              </li>
              <li class="nav-item">
                <p>
                  <%= link_to '#' do %>
                    <i class="bi bi-database-fill"></i>
                    Storage
                  <% end %>
                </p>
                <div class="progress progress-sm active">
                  <div class="progress-bar bg-primary progress-bar-striped" role="progressbar"
                       aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                    <span class="sr-only">40% Complete (success)</span>
                  </div>
                </div>
              </li>
              <p style="color: white;">40% of storage used</p>
              <br>
              <li class="nav-item">
                <p>
                  <%= link_to root_path, class: 'btn btn-primary' do %>
                    <i class="bi bi-database-fill-up"></i>
                    Request More Storage
                  <% end %>
                </p>
                                  
              </li>
            </ul>
          </div>    
        </div>  
      </aside>
      <div class="content-wrapper">
        <section class="content-header">
          <div class="container-fluid">
            <h1 class="text-center">Welcome to <span class="btn btn-lg btn-primary">MediaVault</span></h1>
          <%= yield %>
          </div>    
        </section>  
      </div>  
    </div>  
  </body>
</html>